POST http://localhost:3001/api/notes/
Content-type: application/json

{
  "content": "Very first server data created"
}

###

POST http://localhost:3001/api/notes/
Content-type: application/json

{
  "content": ""
}